language: ruby
before_install: rm -f Gemfile.lock
bundler_args: --full-index
cache: bundler
os:
  - linux
rvm:
  - 2.1.9
  - 2.2.3
  - 2.3.6
  - 2.4.3
  - 2.6.3
script:
  - bundle exec rake test
env:
  global:
     - STRICT_VARIABLES=yes
  matrix:
    - PUPPET_VERSION="~> 4.6.2"
    - PUPPET_VERSION="~> 4.7.1"
    - PUPPET_VERSION="~> 4.8.2"
    - PUPPET_VERSION="~> 4.9.4"
    - PUPPET_VERSION="~> 4.10.9"
    - PUPPET_VERSION="~> 5.0.1"
    - PUPPET_VERSION="~> 5.1.0"
    - PUPPET_VERSION="~> 5.2.0"
    - PUPPET_VERSION="~> 5.3.3"
    - PUPPET_VERSION="~> 6.0.0"
    - PUPPET_VERSION="~> 6.5.0"
matrix:
  exclude:
    # Puppet 6 needs ruby 2.3+
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 6.0.0"
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 6.5.0"
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 6.0.0"
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 6.5.0"
  include:
      os: windows
      rvm: 2.5.3 # Has no effect, but without this Travis shows 2.1.9 in the GUI, which is incorrect
      language: bash # There is no support for ruby on windows yet (2019/09)
      install:
      - choco uninstall ruby # Otherwise we end up with two rubys installed
      - choco install ruby --allow-downgrade -y --version 2.5.3.101 # Keep version in sync with next command!
      - export PATH=/c/tools/ruby25/bin:$PATH # Installing ruby doesn't set the path, we need to do this manually
      - ruby --version
      - choco install msys2 --allow-downgrade -y --version 20180531.0.0
      - ridk.cmd exec pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
      - powershell kill -n gpg-agent # Started by msys, if we don't kill it the travis job stays running forever (found by running 'ps -W')
      - gem install bundler -v 1.17.3
      - bundle install
      env: PUPPET_VERSION="~> 6.5.0"
